version: '2.1'
services:
  server:
    image: server
    platform: linux/x86_64
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - server:/data

volumes:
  server:
