dsn: "postgres://127.0.0.1/go_restful?sslmode=disable&user=postgres&password=postgres"
jwt_signing_key: "LxsKJywDL5O5PvgODZhBH12KE6k2yL8E"
self_app_id: "526fdeac-01b4-4785-a910-085a4f66577a"
self_device_secret: "sk_1:65VvUD5A3qTpPzvozHRXMS6gss0oZJE7PDICdMjs86s"
self_storage_key: "ksdh827hofuasihdjn"
self_storage_dir: "./storage"
self_env: "review"
user: "demo"
password: "pass"
serve_docs: "true"