apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "restful-client.fullname" . }}
  labels:
    {{- include "restful-client.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "restful-client.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "restful-client.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "restful-client.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "restful-client.fullname" . }}
          image: {{ include "restful-client.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.existingSecret }}
            - name: RESTFUL_CLIENT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: {{ .Values.secretKeys.authUsername }}
            - name: RESTFUL_CLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: {{ .Values.secretKeys.authPassword }}
            - name: RESTFUL_CLIENT_JWT_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: {{ .Values.secretKeys.jwtSigningKey }}
            - name: RESTFUL_CLIENT_STORAGE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: {{ .Values.secretKeys.storageKey }}
            - name: RESTFUL_CLIENT_APP_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: {{ .Values.secretKeys.appID }}
            - name: RESTFUL_CLIENT_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: {{ .Values.secretKeys.appSecret }}
            - name: RESTFUL_CLIENT_APP_ENV
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: {{ .Values.secretKeys.appEnvironment }}
            {{- else }}
            {{- if .Values.authUsername }}
            - name: RESTFUL_CLIENT_USER
              value: {{ .Values.authUsername | quote }}
            {{- end }}
            {{- if .Values.authPassword }}
            - name: RESTFUL_CLIENT_PASSWORD
              value: {{ .Values.authPassword | quote }}
            {{- end }}
            {{- if .Values.jwtSigningKey }}
            - name: RESTFUL_CLIENT_JWT_SIGNING_KEY
              value: {{ .Values.jwtSigningKey | quote }}
            {{- end }}
            {{- if .Values.storageKey }}
            - name: RESTFUL_CLIENT_STORAGE_KEY
              value: {{ .Values.storageKey | quote }}
            {{- end }}
            {{- if .Values.appID }}
            - name: RESTFUL_CLIENT_APP_ID
              value: {{ .Values.appID | quote }}
            {{- end }}
            {{- if .Values.appSecret }}
            - name: RESTFUL_CLIENT_APP_SECRET
              value: {{ .Values.appSecret | quote }}
            {{- end }}
            {{- if .Values.appSecret }}
            - name: RESTFUL_CLIENT_APP_ENV
              value: {{ .Values.appEnvironment | quote }}
            {{- end }}
            {{- end }}
            - name: RESTFUL_CLIENT_STORAGE_DIR
              value: {{ .Values.storageDir | quote }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        {{- include "restful-client.labels" . | nindent 8 }}
    spec:
      accessModes:
        {{- range .Values.persistence.accessModes }}
        - {{ . | quote }}
        {{- end }}
      {{- if .Values.persistence.storageClass }}
      storageClassName: {{ .Values.persistence.storageClass | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
  {{- end }}
