// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accounts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "This endpoint retrieves and lists all the accounts that have been configured in the system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Lists all configured accounts.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "The page number to retrieve. Defaults to 1 if not provided.",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "The number of accounts to retrieve per page. Defaults to 10 if not provided.",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Upon successful operation, a paginated list of accounts is returned.",
                        "schema": {
                            "$ref": "#/definitions/account.ExtListResponse"
                        }
                    },
                    "404": {
                        "description": "Not found - The requested resource does not exist, or you don't have permissions to access it",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "This endpoint creates a new account in the system and sends a request to gather public information associated with the account.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Creates a new account.",
                "parameters": [
                    {
                        "description": "The request body must contain the account details in JSON format.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.CreateAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Upon successful account creation, the response will contain the username, resources associated with the account,",
                        "schema": {
                            "$ref": "#/definitions/account.CreateAccountResponse"
                        }
                    },
                    "400": {
                        "description": "If the request body is invalid, a bad request error is returned.",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "403": {
                        "description": "If the user is not authenticated as an admin, a forbidden error is returned.",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "If there is any internal server error, a generic error is returned.",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/accounts/{username}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "This endpoint deletes an existing account from the system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Deletes an existing account.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The username of the account to be deleted.",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Upon successful account deletion, a no content response is returned.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "If the account does not exist or the user is not authenticated as an admin, a not found error is returned.",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "If there is any internal server error, a generic error is returned.",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/accounts/{username}/password": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "This endpoint changes the password for the provided username.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Changes the password for the current user.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The username of the account for which the password is to be changed.",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "The request body must contain the current password and the new password in JSON format.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Upon successful password change, an OK response is returned.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "If the request body is invalid or the current password is incorrect, a bad request error is returned.",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "404": {
                        "description": "If the user does not exist or is not authenticated, a not found error is returned.",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "If there is any internal server error, a generic error is returned.",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/apps": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves and lists all the configured apps for the restful client. You must be authenticated as an admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "apps"
                ],
                "summary": "Lists all configured apps.",
                "responses": {
                    "200": {
                        "description": "Successful operation",
                        "schema": {
                            "$ref": "#/definitions/app.ExtListResponse"
                        }
                    },
                    "404": {
                        "description": "Not found - The requested resource does not exist, or you don't have permissions to access it",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new app with the given parameters. You must be authenticated as an admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "apps"
                ],
                "summary": "Creates a new app.",
                "parameters": [
                    {
                        "description": "Details of the new app to create",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app.CreateAppRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully created app details",
                        "schema": {
                            "$ref": "#/definitions/app.ExtApp"
                        }
                    },
                    "400": {
                        "description": "Bad request - The provided body is not valid",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "404": {
                        "description": "Not found - The requested resource does not exist, or you don't have permissions to access it",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal error - There was a problem with your request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/apps/{app_id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes an existing app and sends a request for public information and avoids incoming comms from that app. You must be authenticated as an admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "apps"
                ],
                "summary": "Deletes an existing app.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the app to delete",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not found - The requested resource does not exist, or you don't have permissions to access it",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/apps/{app_id}/connections": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a list of connections for a given app_id, matching the specified filters. Pagination is supported with optional page and per_page parameters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connections"
                ],
                "summary": "Retrieve a list of connections",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique Identifier for the App",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number for pagination. Default is 1.",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of elements per page for pagination. Default is 10.",
                        "name": "per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful retrieval of connections list",
                        "schema": {
                            "$ref": "#/definitions/connection.ExtListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error occurred during the request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "This API endpoint creates a new connection by taking the application ID and request body as input. It sends a request for public information once the connection is created.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connections"
                ],
                "summary": "Create a new connection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique identifier of the application",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Body containing details of the connection to be created",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/connection.CreateConnectionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully created a new connection and returns the details of the new connection",
                        "schema": {
                            "$ref": "#/definitions/connection.ExtConnection"
                        }
                    },
                    "400": {
                        "description": "Returns when the provided input is invalid",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Returns when there is an internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/apps/{app_id}/connections/{connection_id}/facts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "This endpoint retrieves a list of facts using the provided app_id, connection_id, and other optional filters. The results can be paginated using page and per_page parameters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "facts"
                ],
                "summary": "Retrieve facts based on filters",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique Identifier for the Application",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique Identifier for the Connection",
                        "name": "connection_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number for the results pagination",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results per page",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source of the fact",
                        "name": "source",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by fact",
                        "name": "fact",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved the list of facts",
                        "schema": {
                            "$ref": "#/definitions/fact.ExtListResponse"
                        }
                    },
                    "404": {
                        "description": "The requested resource could not be found or you don't have permission to access it",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "There was a problem with your request. Please try again",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "This endpoint issues a new fact to a specific connection using the provided app_id, connection_id and the request body.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "facts"
                ],
                "summary": "Issue a new fact to a connection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique Identifier for the Application",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique Identifier for the Connection",
                        "name": "connection_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Body containing the details of the fact to be issued",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/fact.CreateFactRequestDoc"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Fact successfully issued",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid input - the provided body is not valid",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "404": {
                        "description": "Not found - the requested resource does not exist, or you don't have permissions to access it",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal error - there was a problem with your request. Please try again",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/apps/{app_id}/connections/{connection_id}/facts/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "This endpoint retrieves the details of a specific fact using the provided app_id, connection_id and fact request id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "facts"
                ],
                "summary": "Retrieve specific fact details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique Identifier for the Application",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique Identifier for the Connection",
                        "name": "connection_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique Identifier for the Fact Request",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved the fact details",
                        "schema": {
                            "$ref": "#/definitions/fact.ExtFact"
                        }
                    },
                    "404": {
                        "description": "The requested fact could not be found or you don't have permission to access it",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes an existing fact for a specific connection identified by app_id, connection_id and the id of the fact to be deleted.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "facts"
                ],
                "summary": "Deletes a fact",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique Identifier for the Application",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique Identifier for the Connection",
                        "name": "connection_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique Identifier for the Fact to be deleted",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Fact successfully deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "The requested resource does not exist, or you don't have permissions to access it",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/apps/{app_id}/connections/{connection_id}/messages": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves all messages for a specific connection within an app. Supports pagination and can filter messages since a specific message ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "List conversation messages.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Return elements since a message ID",
                        "name": "messages_since",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number for results pagination",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results per page for pagination",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Application ID",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Connection ID",
                        "name": "connection_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved list of messages",
                        "schema": {
                            "$ref": "#/definitions/message.ExtListResponse"
                        }
                    },
                    "404": {
                        "description": "Resource not found or unauthorized access",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sends a message to a specific connection within an app. Requires Bearer authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Sends a message.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application ID",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Connection ID",
                        "name": "connection_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request to create a message",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/message.CreateMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Successfully sent message",
                        "schema": {
                            "$ref": "#/definitions/message.Message"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "404": {
                        "description": "Resource not found or unauthorized access",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/apps/{app_id}/connections/{connection_id}/messages/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves details of a specific message identified by its JTI, within the context of a specific app and connection. Requires Bearer authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Gets a message.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application ID",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Connection ID",
                        "name": "connection_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Message ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful retrieval of message details",
                        "schema": {
                            "$ref": "#/definitions/message.Message"
                        }
                    },
                    "404": {
                        "description": "Resource not found or unauthorized access",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates an existing message in a specific connection within an app. Requires Bearer authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Edits a message.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application ID",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Connection ID",
                        "name": "connection_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Message ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request to update a message",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/message.UpdateMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully updated message",
                        "schema": {
                            "$ref": "#/definitions/message.Message"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "404": {
                        "description": "Resource not found or unauthorized access",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a specific message from a specific connection within an app.",
                "tags": [
                    "messages"
                ],
                "summary": "Deletes a message.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application ID",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Connection ID",
                        "name": "connection_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Message ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully deleted message, no content returned"
                    },
                    "404": {
                        "description": "Resource not found or unauthorized access",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/apps/{app_id}/connections/{connection_id}/messages/{id}/read": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "This endpoint allows you to mark a specific message as read in a given application by its connection ID and message ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Marks a specific message as read",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique identifier of the application",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique identifier of the connection",
                        "name": "connection_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique identifier of the message to be marked as read",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully marked the message as read. No content is returned."
                    },
                    "404": {
                        "description": "The requested resource could not be found, or you're not authorized to access it.",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "An error occurred while processing your request. Please try again.",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/apps/{app_id}/connections/{connection_id}/messages/{id}/received": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the status of the specified message to 'received'.",
                "tags": [
                    "messages"
                ],
                "summary": "Marks a message as received",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application ID",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Connection ID",
                        "name": "connection_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Message ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully updated message status to received"
                    },
                    "404": {
                        "description": "Message not found or unauthorized access",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error while processing your request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/apps/{app_id}/connections/{connection_id}/notify": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sends a system notification to the given connection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Sends a system notification.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "App id",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Connection id",
                        "name": "connection_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "system notification",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/notification.SystemNotificationData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/apps/{app_id}/connections/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves the details of a connection using the given selfID and app_id. Ensure you have sufficient permissions to access this information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connections"
                ],
                "summary": "Retrieve connection details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique Identifier for the App",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Unique Identifier for the connection",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful retrieval of connection details",
                        "schema": {
                            "$ref": "#/definitions/connection.ExtConnection"
                        }
                    },
                    "404": {
                        "description": "Unable to find the requested resource or lack of permissions to access it",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "This endpoint updates the properties of an existing connection using the provided app_id, connection id, and the request body.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connections"
                ],
                "summary": "Update a specific connection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique Identifier for the Application",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique Identifier for the Connection to be updated",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Body containing updated details of the connection",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/connection.UpdateConnectionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully updated the connection and returns the updated connection details",
                        "schema": {
                            "$ref": "#/definitions/connection.ExtConnection"
                        }
                    },
                    "400": {
                        "description": "Returns when the provided input is invalid",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "There was a problem with your request. Please try again",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "This endpoint deletes an existing connection using the provided app_id and connection id. After deletion, it sends a request for public information and stops incoming communications from that connection.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connections"
                ],
                "summary": "Delete a specific connection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique Identifier for the Application",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique Identifier for the Connection to be deleted",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully deleted the connection and returns the deleted connection details",
                        "schema": {
                            "$ref": "#/definitions/connection.ExtConnection"
                        }
                    },
                    "404": {
                        "description": "The requested resource could not be found or you don't have permission to access it",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/apps/{app_id}/requests": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sends a request request to the specified self user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requests"
                ],
                "summary": "Sends a request request.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "App id",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/request.ExtRequest"
                        }
                    }
                }
            }
        },
        "/apps/{app_id}/requests/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get request details by request request id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requests"
                ],
                "summary": "Get request details.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "App id",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Request request id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/request.ExtRequest"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "This endpoint authenticates user credentials (username and password) and, upon successful authentication,",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Authenticate User and Retrieve Tokens",
                "parameters": [
                    {
                        "description": "Login credentials object containing 'username' and 'password' fields.",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Authentication successful: Returns the JWT for API access and a refresh token.",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request: The request is malformed or the JSON body cannot be parsed.",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: Authentication failed due to invalid credentials or inactive user account.",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error: An unexpected error occurred while processing the authentication request.",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "This endpoint is used to refresh an expired or about to expire JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Refresh JWT Token",
                "parameters": [
                    {
                        "description": "Contains the refresh token that needs to be validated and exchanged for a new JWT token.",
                        "name": "refreshToken",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "A new JWT token is successfully generated and returned along with its expiry information.",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request: The request is invalid or malformed. The error message provides more details.",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: The provided refresh token is invalid or expired, and a new JWT token cannot be issued.",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error: An unexpected error occurred while processing the refresh token request.",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/healthcheck": {
            "get": {
                "description": "check the service is up and running",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck"
                ],
                "summary": "healthcheck endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "account.ChangePasswordRequest": {
            "type": "object",
            "properties": {
                "new_password": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "account.CreateAccountRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "requires_password_change": {
                    "type": "boolean"
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "account.CreateAccountResponse": {
            "type": "object",
            "properties": {
                "requires_password_change": {
                    "type": "boolean"
                },
                "resources": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "account.ExtAccount": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "requires_password_change": {
                    "type": "boolean"
                },
                "resources": {
                    "type": "string"
                }
            }
        },
        "account.ExtListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/account.ExtAccount"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_count": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "app.CreateAppRequest": {
            "type": "object",
            "properties": {
                "callback": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "secret": {
                    "type": "string"
                }
            }
        },
        "app.ExtApp": {
            "type": "object",
            "properties": {
                "env": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "app.ExtListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/app.ExtApp"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_count": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "auth.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "description": "Password password to authenticate with. Length has to be between 5 and\n128 characters.",
                    "type": "string"
                },
                "username": {
                    "description": "Username the username to authenticate with. Length has to be between 5 and\n128 characters.",
                    "type": "string"
                }
            }
        },
        "auth.LoginResponse": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "description": "RefreshToken the token to be used to refresh the access token.",
                    "type": "string"
                },
                "token": {
                    "description": "AccessToken the token to be used on authenticated requests.",
                    "type": "string"
                }
            }
        },
        "auth.RefreshRequest": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "description": "RefreshToken the token to be used to refresh the access token.",
                    "type": "string"
                }
            }
        },
        "connection.CreateConnectionRequest": {
            "type": "object",
            "properties": {
                "selfid": {
                    "type": "string"
                }
            }
        },
        "connection.ExtConnection": {
            "type": "object",
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "connection.ExtListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/connection.ExtConnection"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_count": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "connection.UpdateConnectionRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "fact.CreateFactRequestDoc": {
            "type": "object",
            "properties": {
                "facts": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "group": {
                                "type": "object",
                                "properties": {
                                    "icon": {
                                        "type": "string"
                                    },
                                    "name": {
                                        "type": "string"
                                    }
                                }
                            },
                            "key": {
                                "type": "string"
                            },
                            "source": {
                                "type": "string"
                            },
                            "type": {
                                "type": "string"
                            },
                            "value": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "fact.ExtFact": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "iss": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "values": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "fact.ExtListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/fact.ExtFact"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_count": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "message.CreateMessageRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "options": {
                    "$ref": "#/definitions/message.MessageOptions"
                }
            }
        },
        "message.ExtListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/message.Message"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_count": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "message.Message": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "cid": {
                    "type": "string"
                },
                "connection_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "iat": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "read": {
                    "type": "boolean"
                },
                "received": {
                    "type": "boolean"
                },
                "rid": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "message.MessageObject": {
            "type": "object",
            "properties": {
                "expires": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "mime": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "message.MessageOptions": {
            "type": "object",
            "properties": {
                "objects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/message.MessageObject"
                    }
                }
            }
        },
        "message.UpdateMessageRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                }
            }
        },
        "notification.SystemNotificationData": {
            "type": "object",
            "properties": {
                "metadata": {
                    "type": "object",
                    "properties": {
                        "payload": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string"
                        }
                    }
                },
                "notification": {
                    "type": "object",
                    "properties": {
                        "message": {
                            "type": "string"
                        },
                        "title": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "request.CreateRequest": {
            "type": "object"
        },
        "request.ExtRequest": {
            "type": "object",
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "deep_link": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "qr_code": {
                    "type": "string"
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.ExtResource"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "request.ExtResource": {
            "type": "object",
            "properties": {
                "connection_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "request.FactRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "sources": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "response.Error": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1/",
	Schemes:          []string{"http", "https"},
	Title:            "Joinself restful-client API",
	Description:      "This is the api for Joinself restful client.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
