name: CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  license-compliance:
    uses: joinself/github-workflows-public/.github/workflows/license-compliance.yml@main
    secrets: inherit
  secret-scan:
    uses: joinself/github-workflows-public/.github/workflows/secret-scan.yml@main
    with:
      continue-on-error: true
    secrets: inherit
  #build:
  #  #uses: ./.github/workflows/build-go.yml
  #  uses: joinself/github-workflows/.github/workflows/build-go.yml@main
  #  with:
  #    dockerfile-path: ./cmd/server/Dockerfile
  #  secrets: inherit
  test:
    needs: [license-compliance, secret-scan]
    uses: ./.github/workflows/test.yml
    secrets: inherit
  #publish:
  #  if: ${{ false }}
  #  #if: ${{ github.ref == 'refs/heads/main' }}
  #  needs: test
  #  uses: joinself/github-workflows/.github/workflows/publish-k8s.yml@main
  #  secrets: inherit
