name: _publish

on:
  workflow_call:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    container:
      image: joinself/tools
    steps:
      - name: Setup job
        uses: joinself/github-actions-public/setup-job@main
      - name: Publish
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_CI_CI: ${{ secrets.SLACK_WEBHOOK_CI_CI }}
          CONTAINER_REGISTRY_URL: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env
          echo "${GH_TOKEN}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          helm package helm/chart
          pkg_name=$(ls *.tgz)
          helm push ${pkg_name} oci://ghcr.io/joinself/charts
      - name: Failure notification
        if: ${{ github.ref == 'refs/heads/main' && failure() }}
        uses: joinself/github-actions-public/failure-notification@main
        with:
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_CI_ALERTS }}
