name: _test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    # container:
    #   image: golang:1.19.1-bullseye
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: go_restful
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Setup job
        uses: joinself/github-actions-public/setup-job@main
      - name: Test
        shell: bash
        env:
          APP_ENV: local
          APP_DSN: "postgres://localhost/go_restful?sslmode=disable&user=${{ secrets.POSTGRES_USER }}&password=${{ secrets.POSTGRES_PASSWORD }}"
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env
          #apt-get update
          #apt-get install -y --no-install-recommends curl libsodium-dev
          #curl https://download.joinself.com/olm/libself-olm_0.1.17_amd64.deb -o /tmp/libself-olm_0.1.17_amd64.deb
          #curl https://download.joinself.com/omemo/libself-omemo_0.1.3_amd64.deb -o /tmp/libself-omemo_0.1.3_amd64.deb
          #apt-get install -y --no-install-recommends /tmp/libself-olm_0.1.17_amd64.deb /tmp/libself-omemo_0.1.3_amd64.deb
          curl -Lo /tmp/go.tar.gz https://go.dev/dl/go1.19.1.linux-amd64.tar.gz
          tar -C /usr/local -zxf /tmp/go.tar.gz
          PATH="${PATH}:/usr/local/go/bin"
          go version
          curl -Lo /tmp/self-omemo.deb https://github.com/joinself/self-omemo/releases/download/0.5.0/self-omemo_0.5.0_amd64.deb
          apt-get install -y /tmp/self-omemo.deb
          curl -Lo /tmp/migrate.tar.gz https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz
          tar zxf /tmp/migrate.tar.gz -C /tmp
          cp /tmp/migrate /usr/local/bin/

          # lint check
          curl -Lo /tmp/golangci-lint.tar.gz https://github.com/golangci/golangci-lint/releases/download/v1.21.0/golangci-lint-1.21.0-linux-amd64.tar.gz
          tar zxf /tmp/golangci-lint.tar.gz -C /tmp
          cp /tmp/golangci-lint-1.21.0-linux-amd64/golangci-lint /usr/local/bin
          make lint

          # build
          make build

          # test
          make migrate
          make test-cover
      - name: Failure notification
        if: ${{ github.ref == 'refs/heads/main' && failure() }}
        uses: joinself/github-actions-public/failure-notification@main
        with:
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_CI_ALERTS }}
