name: _test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup job
        uses: joinself/github-actions-public/setup-job@main
      - name: Test
        shell: bash
        env:
          RESTFUL_CLIENT_JWT_SIGNING_KEY: secret
          RESTFUL_CLIENT_USER: self
          RESTFUL_CLIENT_PASSWORD: secret
          RESTFUL_CLIENT_STORAGE_DIR: /tmp
          RESTFUL_CLIENT_STORAGE_KEY: secret
          RESTFUL_CLIENT_APP_ID: c4f81d86-9dac-40fd-9830-13c66a0b2345
          RESTFUL_CLIENT_APP_SECRET: sk_1:56qJGhYCJmTHsYChCp3sPSjmiGlN2yG0KakYDquMAD0
          RESTFUL_CLIENT_APP_ENV: review
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env
          curl -Lo /tmp/go.tar.gz https://go.dev/dl/go1.21.3.linux-amd64.tar.gz
          sudo tar -zxf /tmp/go.tar.gz -C /usr/local
          PATH="${PATH}:/usr/local/go/bin"
          curl -Lo /tmp/self-omemo.deb https://github.com/joinself/self-omemo/releases/download/0.5.0/self-omemo_0.5.0_amd64.deb
          sudo apt-get install -y /tmp/self-omemo.deb
          curl -Lo /tmp/migrate.tar.gz https://download.joinself.com/golang-migrate/migrate-sqlite3-4.16.2.tar.gz && \
          sudo tar -zxf /tmp/migrate.tar.gz -C /usr/local/bin
          curl -Lo /tmp/golangci-lint.tar.gz https://github.com/golangci/golangci-lint/releases/download/v1.21.0/golangci-lint-1.21.0-linux-amd64.tar.gz
          tar -zxf /tmp/golangci-lint.tar.gz -C /tmp
          sudo cp /tmp/golangci-lint-1.21.0-linux-amd64/golangci-lint /usr/local/bin
          echo "hit1"
          go version
          echo "hit2"
          make lint
          echo "hit3"
          make build
          echo "hit4"
          make migrate
          make test
      - name: Failure notification
        if: ${{ github.ref == 'refs/heads/main' && failure() }}
        uses: joinself/github-actions-public/failure-notification@main
        with:
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_CI_ALERTS }}
